apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv
  namespace: ldap
spec:
  storageClassName: ldap
  nfs:
    path: /data/nfs-volume/ldap
    server: 10.0.0.20
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi