{
 "title": "blackbox 黑盒测试",
 "description": "blackbox_exporter 0.16.0 / 2019-11-11",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "项目",
    "query": {
     "query": "label_values(probe_success, project)"
    }
   },
   {
    "name": "protocol",
    "label": "protocol",
    "query": {
     "query": "label_values(probe_success{project=~\"$project\"}, protocol)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(probe_success{project=~\"$project\",protocol=~\"$protocol\"}, env)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(probe_success{project=~\"$project\",protocol=~\"$protocol\",env=~\"$env\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(probe_success{project=~\"$project\",protocol=~\"$protocol\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总耗时",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\",env=~\"$env\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "状态码",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "连通性",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "阶段耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"}",
     "legendFormat": "{{instance}} {{phase}}"
    },
    {
     "expr": "sum by (phase) (probe_http_duration_seconds{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (phase) (probe_icmp_duration_seconds{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "状态明细",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "probe_success{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\",env=~\"$env\"} - 0"
    },
    {
     "expr": "probe_http_ssl{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\",env=~\"$env\"} - 0"
    },
    {
     "expr": "probe_http_status_code{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\",env=~\"$env\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\",instance=~\"$instance\",service=~\"$service\",protocol=~\"$protocol\",env=~\"$env\"} - time()"
    }
   ]
  }
 ]
}