{
 "title": "docker-compose容器监控展示看板",
 "description": "Docker monitoring with Prometheus and cAdvisor with node selection",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_com_docker_compose_project!=\"\"}, node)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_com_docker_compose_project != \"\",node=\"$node\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "启动的容器数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "使用的总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"})/1024/1024"
    }
   ]
  },
  {
   "title": "CPU总使用量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[$interval]) * 100",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "网络接收速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "网络发送速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "硬盘读取速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "硬盘写入速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{node=~\"$node\",container_label_com_docker_compose_project != \"\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  }
 ]
}