{
 "title": "k8s容器监控展示看板",
 "description": "Docker monitoring with Prometheus and cAdvisor with node selection",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "NameSpace",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\",cluster=~\"$cluster\"},container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\",cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_container_name!=\"POD\"}, container_label_io_kubernetes_container_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\",cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_container_name=~\"$container\"}, container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "host",
    "label": "node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\",cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",container_label_io_kubernetes_container_name=~\"$container\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$host：节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$host\"}) / sum (machine_memory_bytes{node=~\"$host\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$host\"}) / sum(kube_node_status_capacity_memory_bytes{node=~\"$host\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$host\"}) / sum(kube_node_status_capacity_memory_bytes{node=~\"$host\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "$host：节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$host\"}[2m])) / sum (machine_cpu_cores{node=~\"$host\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$host\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$host\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$host\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$host\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "$host：节点与Pod",
   "type": "bargauge",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"$host\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"$host\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$host\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "命名空间明细",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"$host\",namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{node=~\"$host\",namespace=~\"$namespace\"}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{node=~\"$host\",namespace=~\"$namespace\"}) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{node=~\"$host\",namespace=~\"$namespace\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{node=~\"$host\",namespace=~\"$namespace\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$namespace：网络总览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"$host\",container_label_io_kubernetes_pod_namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{node=~\"$host\",container_label_io_kubernetes_pod_namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "$host：节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"$host\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$host\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$host\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$host\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "$host：节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"$host\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"$host\"}[2m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$host\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$host\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "$host：节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "$host：集群节点信息明细",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"$host\"}) by (node)",
     "legendFormat": "pod数"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",node=~\"$host\"}  == 1",
     "legendFormat": "状态"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$host\"}[3m])) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=~\"$host\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$host\"}) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{node=~\"$host\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$host\"})by (node) / sum (machine_memory_bytes{})by (node)",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$host\"})by (node) / sum(kube_node_status_capacity_memory_bytes{node=~\"$host\"})by (node)",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$host\"})by (node) / sum(kube_node_status_capacity_memory_bytes{node=~\"$host\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$host\"}[2m]))by (node) / sum (machine_cpu_cores{node=~\"$host\"})by (node)",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$host\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$host\"})by (node)",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$host\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$host\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"})by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$host\"})by (node)",
     "legendFormat": "磁盘使用%"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$host\"})by (node)",
     "legendFormat": "Pod上限"
    }
   ]
  },
  {
   "title": "启动的容器数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",node=~\"$host\"})"
    }
   ]
  },
  {
   "title": "使用的总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 18 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\"})/1024/1024"
    }
   ]
  },
  {
   "title": "CPU总使用量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\",container_label_io_kubernetes_container_name=~\"$container\"}[$interval]) * 100)by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\",container_label_io_kubernetes_container_name=~\"$container\"})by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "硬盘使用信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\",container_label_io_kubernetes_container_name=~\"$container\"}[$interval]))by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "读取：{{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{cluster=~\"$cluster\",container_label_io_kubernetes_pod_namespace=~\"$namespace\",container_label_io_kubernetes_pod_name=~\"$pod\",node=~\"$host\",container_label_io_kubernetes_container_name=~\"$container\"}[$interval]))by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "写入：{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "微服务(容器名)每秒网络带宽 ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"$pod\",name=~\"^k8s_.*\",node=~\"$host\",container_label_io_kubernetes_pod_namespace=~\"$namespace\"}[2m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "流入:{{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": " sum (rate (container_network_transmit_bytes_total{container_label_io_kubernetes_pod_name=~\"$pod\",name=~\"^k8s_.*\",node=~\"$host\",container_label_io_kubernetes_pod_namespace=~\"$namespace\"}[2m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "流出:{{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  }
 ]
}