{
 "title": "k8s容器监控展示看板",
 "description": "Docker monitoring with Prometheus and cAdvisor with node selection",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{container_label_io_kubernetes_pod_uid!=\"\"}, node)"
    }
   },
   {
    "name": "NameSpace",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{node=\"$node\"},container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{node=\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}, container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "启动的容器数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"$node\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "使用的总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"})/1024/1024"
    }
   ]
  },
  {
   "title": "CPU总使用量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[$interval]) * 100)by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"})by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "网络接收速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[$interval]))by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "网络发送速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[$interval]))by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "硬盘读取速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[$interval]))by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "硬盘写入速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{node=~\"$node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",container_label_io_kubernetes_pod_name=~\"$pod\"}[$interval]))by(container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}