{
 "title": "Kubernetes for Prometheus Dashboard CN",
 "tags": [
  "StarsL.cn",
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$origin_prometheus\",node=~\"$Node\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "微服务(容器名)",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",node=~\"$Node\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",node=~\"$Node\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "节点资源总览：所选节点:【$Node】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "节点与Pod",
   "type": "bargauge",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{origin_prometheus=~\"$origin_prometheus\",node=~\"$Node\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "命名空间明细",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：网络总览（关联节点与命名空间）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "$Node：节点信息明细",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "pod数"
    },
    {
     "expr": "kube_node_status_condition{origin_prometheus=~\"$origin_prometheus\",status=\"true\",node=~\"^$Node$\"}  == 1",
     "legendFormat": "状态"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[3m])) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))by (node) / sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "磁盘使用%"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Pod上限"
    }
   ]
  },
  {
   "title": "微服务与Pod资源汇总",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)资源统计",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_container_name) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}/100000) by (container_label_io_kubernetes_container_name)) * 100"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_container_name)",
       "legendFormat": "整体核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name) * 100"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name) * 100",
       "legendFormat": "平均内存%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)",
       "legendFormat": "总内存使用(RSS) "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)"
      },
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by(container) - 0"
      }
     ]
    },
    {
     "title": "Pod资源明细",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"} == 1"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}/100000) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)",
       "legendFormat": "CPU核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container,pod)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container,pod)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name,container_label_io_kubernetes_pod_name)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"$Node\"} - 0"
      },
      {
       "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "微服务与Pod资源曲线图（请在菜单中指定微服务后查看，以免卡顿）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)整体CPU使用率(最大100%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[1m])) by (container_label_io_kubernetes_container_name) * 1000",
       "legendFormat": "{{ container_label_io_kubernetes_container_name }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体内存使用率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name) * 100",
       "legendFormat": "WSS：{{ container_label_io_kubernetes_container_name }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name) * 100",
       "legendFormat": "RSS：{{ container_label_io_kubernetes_container_name }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体内存使用量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_container_name =~\"$Container\",container_label_io_kubernetes_container_name !=\"\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container_label_io_kubernetes_container_name)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_container_name =~\"$Container\",container_label_io_kubernetes_container_name !=\"\",container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container_label_io_kubernetes_container_name)",
       "legendFormat": "RSS：{{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"$Node\"}) by (container)",
       "legendFormat": "limits：{{ container }}"
      }
     ]
    },
    {
     "title": "Pod容器CPU使用率(可关联节点)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name=~\"$Container\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[1m])) by (container_label_io_kubernetes_pod_name) * 1000",
       "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Pod容器内存使用率(可关联节点)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name) * 100",
       "legendFormat": "WSS：{{ container_label_io_kubernetes_pod_name }}：{{container_label_io_kubernetes_container_name}}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name) * 100",
       "legendFormat": "RSS：{{ container_label_io_kubernetes_pod_name }}：{{container_label_io_kubernetes_container_name}}"
      },
      {
       "expr": "(cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) / (cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) * 100",
       "legendFormat": "Heap：{{ pod }}：{{container}}"
      }
     ]
    },
    {
     "title": "Pod容器内存使用量(可关联节点)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",container_label_io_kubernetes_container_name !=\"\",container_label_io_kubernetes_container_name!=\"POD\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name)",
       "legendFormat": "WSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",container_label_io_kubernetes_container_name !=\"\",container_label_io_kubernetes_container_name!=\"POD\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace\n=~\"$NameSpace\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name)",
       "legendFormat": "RSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container,pod)",
       "legendFormat": "limits：{{ pod }}：{{container}}"
      },
      {
       "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}",
       "legendFormat": "Heap：{{ pod }}：{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "微服务网络带宽",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)每秒网络带宽 (可关联节点与Pod)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",container_label_io_kubernetes_container_name =~\"$Container\",node=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "流入:{{ container_label_io_kubernetes_pod_name }}"
      },
      {
       "expr": " sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",container_label_io_kubernetes_pod_name=~\"$Pod\",name=~\"^k8s_.*\",node=~\"$Node\",container_label_io_kubernetes_pod_namespace=~\"$NameSpace\"}[2m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "流出:{{ container_label_io_kubernetes_pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}